const values = [
  'tells someone to fuck themselves',
  'eat the rich',
  'works on his machine',
  'uses the word pleeb',
  'talks about D&D',
  'Americans are idiots',
  'Javascript is dumb',
  'says something NSFW',
  'commits a fireable offense',
  'works less than 30 min',
  'complains about sales',
  'MBAs are useless',
  'earns a whiteboard quote',
  'raises middle finger',
  'raises 2 middle fingers',
  'talks about unionizing',
  'Manhattan is the best',
  'NJ is the worst',
  'Anything about Hawaii',
  'Frankly I dont give a damn/fuck',
  'brings up blackjack and hookers',
  'uses homer gif',
  'distracts you from work',
  'gets distracted from work',
  'soup is a meal',
  'upper west side is a suburb',
  'advocates dictatorship',
  'talks about boxing',
  'doesnt care about ui',
  'bulgaria is a shithole',
  'bulgaria does something better',
  'Nyers are so nice',
  'mentions the Alabamians',
  'Long Island hicks',
  'I miss George',
  'tells someone they are wrong',
  'does hair flip',
  'steals snacks',
  'says something sexual by accident',
  'talks about wearing kilts',
  'talks about committing crimes',
  'complains about Jim',
  'NJ transit works because of me',
  'No mountains in the northeast',
  'Florida is great',
  'yodo',
  '"literally trash/garbage"',
  'macs/apple is shitty',
  'calls mike flaky',
  'complains about someone elses coding style'
];
export default values;
